### ISSUE TITLE
Visual Studio support

### ISSUE THREAD

**Issue by Arnab-Developer** [madebygps/timestamper-api#2]
@madebygps do you want Visual Studio support in your project? If you add a `solution` file and include all the three `projects` in it, then people can open that `solution` file in Visual Studio and work with this project.

If you want Visual Studio support, then can I send a pull request?

**Comment by madebygps** [comment]
Yeah sure go for it :)

**Comment by Arnab-Developer** [comment]
Thanks @madebygps 

I have created a PR for this which is ready for your review.
